"""Demo expiry gate for SwiftMedics demonstration builds.

A demo .exe handed to a hospital must stop working after an agreed date. The
expiry is COMPILED INTO THE BUILD as ``speechmatics_test/demo_build_stamp.py``
(generated by ``scripts/set_demo_expiry.py``; the file is git-ignored). When
the stamp file is absent the gate is inactive and this module is a no-op, so
development and the full product build are unaffected.

Deliberate properties:

* The compiled-in stamp is generated, never hand-edited, and never committed.
* The check compares against the real wall clock; users cannot pass a demo
  build by moving it to another machine, only by tampering with the binary or
  the system clock (both out of scope for a demonstration build).
* ``days_remaining`` lets the UI show a friendly banner instead of a hard
  failure while the demo is still valid.
"""
from __future__ import annotations

import datetime as _dt
import json
import time
from pathlib import Path

try:  # generated by scripts/set_demo_expiry.py; absent outside demo builds
    from .demo_build_stamp import DEMO_EXPIRY, DEMO_BUILD_ID, DEMO_BROKER_URL
except ImportError:  # not a demo build
    DEMO_EXPIRY = None
    DEMO_BUILD_ID = None
    DEMO_BROKER_URL = None

try:  # reuse the app's per-user data dir when available
    from .desktop_config import app_data_dir
except Exception:  # pragma: no cover - keeps the module importable standalone
    app_data_dir = None  # type: ignore[assignment]

#: How far the clock may move backwards (NTP corrections, timezone travel)
#: before the build is treated as tampered. UTC epoch is used internally, so
#: timezone changes never trip this by themselves.
_CLOCK_TOLERANCE_SECONDS = 24 * 3600

__all__ = [
    "DEMO_EXPIRY",
    "DEMO_BUILD_ID",
    "DEMO_BROKER_URL",
    "days_remaining",
    "check_demo_license",
]


def days_remaining(now: _dt.datetime | None = None) -> int | None:
    """Whole days until expiry, ``0`` on/after expiry, ``None`` when inactive."""
    if DEMO_EXPIRY is None:
        return None
    now = now or _dt.datetime.now()
    return max(0, (DEMO_EXPIRY - now).days)


def _state_path() -> Path | None:
    """Per-user watermark file, next to the desktop config."""
    if app_data_dir is None:
        return None
    try:
        return Path(app_data_dir()) / "demo_state.json"
    except Exception:  # pragma: no cover - defensive
        return None


def _read_watermark(path: Path | None) -> float:
    if path is None:
        return 0.0
    try:
        value = json.loads(path.read_text(encoding="utf-8")).get(
            "latest_seen_epoch", 0.0
        )
        return float(value) if isinstance(value, (int, float)) else 0.0
    except Exception:  # missing/corrupt file = first run
        return 0.0


def _write_watermark(path: Path | None, value: float) -> None:
    if path is None:
        return
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps({"latest_seen_epoch": value}), encoding="utf-8")
    except OSError:
        # Best effort only: a read-only profile must not break the demo.
        pass


def _update_clock_watermark(monotonic_now: float | None = None) -> None:
    """Detect system-clock rollback past the highest time ever seen.

    The expiry date is checked against the wall clock, so moving the clock
    back would otherwise reset the demo forever. A per-user high-water mark
    of UTC epoch time closes that hole up to the tolerance (NTP corrections,
    timezone travel). An attacker who also edits or deletes the state file is
    out of scope for a demonstration build; the compiled Nuitka layer is the
    real boundary there.
    """
    if DEMO_EXPIRY is None:
        return
    path = _state_path()
    now = monotonic_now if monotonic_now is not None else time.time()
    seen = _read_watermark(path)
    if seen and now < seen - _CLOCK_TOLERANCE_SECONDS:
        raise DemoLicenseExpired(
            "The system clock appears to have been moved backwards. "
            "Set the correct date and time, then try again."
        )
    _write_watermark(path, max(now, seen))


def check_demo_license(now: _dt.datetime | None = None) -> None:
    """Raise ``DemoLicenseExpired`` when a demo build is used past its expiry
    date, or after a detected system-clock rollback."""
    if DEMO_EXPIRY is None:
        return
    _update_clock_watermark()
    now = now or _dt.datetime.now()
    if now >= DEMO_EXPIRY:
        raise DemoLicenseExpired(
            "This SwiftMedics demonstration build expired on "
            f"{DEMO_EXPIRY:%Y-%m-%d}. Contact the vendor for an updated build."
        )


class DemoLicenseExpired(RuntimeError):
    """Raised when a demonstration build is used after its expiry date."""
