"""Demo expiry gate for SwiftMedics demonstration builds.

A demo .exe handed to a hospital must stop working after an agreed date. The
expiry is COMPILED INTO THE BUILD as ``speechmatics_test/demo_build_stamp.py``
(generated by ``scripts/set_demo_expiry.py``; the file is git-ignored). When
the stamp file is absent the gate is inactive and this module is a no-op, so
development and the full product build are unaffected.

Deliberate properties:

* The compiled-in stamp is generated, never hand-edited, and never committed.
* The check compares against the real wall clock; users cannot pass a demo
  build by moving it to another machine, only by tampering with the binary or
  the system clock (both out of scope for a demonstration build).
* ``days_remaining`` lets the UI show a friendly banner instead of a hard
  failure while the demo is still valid.
"""
from __future__ import annotations

import datetime as _dt

try:  # generated by scripts/set_demo_expiry.py; absent outside demo builds
    from .demo_build_stamp import DEMO_EXPIRY, DEMO_BUILD_ID, DEMO_BROKER_URL
except ImportError:  # not a demo build
    DEMO_EXPIRY = None
    DEMO_BUILD_ID = None
    DEMO_BROKER_URL = None

__all__ = [
    "DEMO_EXPIRY",
    "DEMO_BUILD_ID",
    "DEMO_BROKER_URL",
    "days_remaining",
    "check_demo_license",
]


def days_remaining(now: _dt.datetime | None = None) -> int | None:
    """Whole days until expiry, ``0`` on/after expiry, ``None`` when inactive."""
    if DEMO_EXPIRY is None:
        return None
    now = now or _dt.datetime.now()
    return max(0, (DEMO_EXPIRY - now).days)


def check_demo_license(now: _dt.datetime | None = None) -> None:
    """Raise ``DemoLicenseExpired`` when a demo build is past its expiry."""
    if DEMO_EXPIRY is None:
        return
    now = now or _dt.datetime.now()
    if now >= DEMO_EXPIRY:
        raise DemoLicenseExpired(
            "This SwiftMedics demonstration build expired on "
            f"{DEMO_EXPIRY:%Y-%m-%d}. Contact the vendor for an updated build."
        )


class DemoLicenseExpired(RuntimeError):
    """Raised when a demonstration build is used after its expiry date."""
