"""Generate the compiled-in demo expiry stamp for a demonstration build.

Run BEFORE building the demo .exe (on the build machine, never committed —
the file is git-ignored):

    python scripts/set_demo_expiry.py --date 2026-11-30
    python scripts/set_demo_expiry.py --date 2026-11-30 --build-id hospital-x-demo

This writes ``speechmatics_test/demo_build_stamp.py``, which
``speechmatics_test/demo_license.py`` reads at runtime. To return the
repository to a non-demo state, delete that file.
"""
from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STAMP_PATH = ROOT / "speechmatics_test" / "demo_build_stamp.py"

TEMPLATE = (
    '"""Generated by scripts/set_demo_expiry.py - do not edit or commit."""\n\n'
    "import datetime\n\n"
    "DEMO_EXPIRY = datetime.datetime({y}, {m}, {d}, 23, 59, 59)\n"
    "DEMO_BUILD_ID = {build_id!r}\n"
    "DEMO_BROKER_URL = {broker_url!r}\n"
)


def write_stamp(expiry: dt.date, build_id: str, broker_url: str) -> Path:
    STAMP_PATH.parent.mkdir(parents=True, exist_ok=True)
    STAMP_PATH.write_text(
        TEMPLATE.format(
            y=expiry.year,
            m=expiry.month,
            d=expiry.day,
            build_id=build_id,
            broker_url=broker_url,
        ),
        encoding="utf-8",
    )
    return STAMP_PATH


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Set the SwiftMedics demo expiry date")
    parser.add_argument("--date", required=True, help="expiry date, YYYY-MM-DD (inclusive)")
    parser.add_argument("--build-id", default="", help="optional label recorded in the build")
    parser.add_argument(
        "--broker-url",
        default="",
        help="default token broker URL compiled into the demo build "
        "(the demo config does not need a long-lived API key)",
    )
    args = parser.parse_args(argv)

    try:
        expiry = dt.date.fromisoformat(args.date)
    except ValueError:
        parser.error(f"--date must be YYYY-MM-DD, got {args.date!r}")
        return 2

    build_id = args.build_id.strip() or f"demo-{expiry.isoformat()}"
    broker_url = args.broker_url.strip()
    if broker_url and not broker_url.lower().startswith("https://"):
        parser.error("--broker-url must be an https URL")
        return 2
    path = write_stamp(expiry, build_id, broker_url)
    print(f"Demo stamp written: {path}")
    print(f"  expiry    : {expiry.isoformat()} (23:59:59 local time)")
    print(f"  build id  : {build_id}")
    if broker_url:
        print(f"  broker    : {broker_url}")
    print(
        "Now build the demo bundle, e.g.:  .\\scripts\\build_demo.ps1 -ExpiryDate "
        + expiry.isoformat()
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
